import pytest


class TestException(Exception): ...
